---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: developer-portal
spec:
  owner: guests
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  title: Backstage
  name: backstage
  description: An example of a Backstage application backend.
  # Example for optional annotations
  annotations:
    github.com/project-slug: tpoingt/backstage-cncf
    backstage.io/linguist:  https://github.com/tpoingt/backstage-cncf
    # backstage.io/techdocs-ref: dir:.
    prometheus.io/alert: BackstageHighErrorRate
    prometheus.io/rule: slo:sli_error:ratio_rate5m{sloth_service="backstage"}
spec:
  system: developer-portal
  type: service
  owner: guests
  lifecycle: experimental
  providesApis:
    - internal_backstage_openapi_doc
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  title: Backstage SPA
  name: backstage-app
  description: An example of a Backstage application frontend.
  # Example for optional annotations
  annotations:
    github.com/project-slug: tpoingt/backstage-cncf
    backstage.io/linguist:  https://github.com/tpoingt/backstage-cncf
    # backstage.io/techdocs-ref: dir:.
spec:
  system: developer-portal
  type: website
  owner: guests
  lifecycle: experimental